#!/bin/bash
# :::::::::::::::::::::#
## TRISNA SAutoInstall ##
#::::::::::::::::::::::#
# Namespace: TSAI #
# Versi: 1.0 #
# Modify: Zerticcarver #
# Updated: 14/3/2021 #
# Update Info: xedocst.xerosoftio.eu.org #
#:::::::::::::::::::::::::::::::::::::::#
# Created by © TRISNA797#
#:::::::::::::::::::::::::::::::::::::::#
color1='\e[031;1m'
color2='\e[34;1m'
color3='\e[0m'

clear
echo -e "${color1}========================================${color3}"
echo -e "* ${color2}SCRIPT AUTO INSTALL BY KingKongVPN ${color3}*"
echo -e "${color1}========================================${color3}"
echo -e " "
echo -e "This Menu Still Under Development,Please Use Menu 1"
rm 'Menu 2'
